name: CI Build

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check
        run: |
          set -o pipefail
          pnpm check | tee result

      - name: Print Summary
        run: |
          echo "## Check Result" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat result)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY