name: 'Storybook Deployment'

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Build and Publish
        run: |
          pnpm install
          pnpm deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
             
